### ISSUE TITLE
minor: can segfault on error

### ISSUE THREAD

**Issue by ttDSSD-EMC** [MicronSSD/unvme#5]
When I previously had the VFIO_IOVA too large, libunvme produced a segfault because
 vfio_dma_free get's called with NULL:

```
(gdb) bt
#0  0x0000000000404f1d in vfio_dma_free (dma=0x0) at unvme_vfio.c:542
#1  0x0000000000402997 in unvme_adminq_delete (adminq=0x6093b0) at unvme.c:267
#2  0x0000000000402cd0 in unvme_session_delete (ses=0x6092f0) at unvme.c:335
#3  0x0000000000402f8a in unvme_cleanup () at unvme.c:371
#4  0x000000000040286a in unvme_adminq_create (ses=0x6092f0) at unvme.c:250
#5  0x0000000000402b86 in unvme_session_create (nsid=0, qcount=1, qsize=8) at unvme.c:298
#6  0x0000000000402f17 in unvme_init (pci=65536) at unvme.c:361
#7  0x0000000000403030 in unvme_do_open (pci=65536, nsid=1, qcount=1, qsize=16) at unvme.c:388
#8  0x00000000004015be in unvme_open (pciname=0x7fffffffe219 "01:00.0", nsid=1, qcount=1, qsize=16) at libunvme.c:75
```

**Comment by dhongMicron** [comment]
Thanks for finding all these conditions.  I've checked in the fix.

**Comment by ttDSSD-EMC** [comment]
It think this can be closed.  Was there a particular reason it was reopened?
